### ISSUE TITLE
raw data no longer available for download

### ISSUE THREAD

**Issue by malcook** [lmweber/cytometry-clustering-comparison#3]
I find that some of the data required to run your comparisons is no longer available, specifically:

| prepare_data_FlowCAP_ND.R   | manual gating data unavailable                                     |
| prepare_data_FlowCAP_WNV.R  | manual gating data unavailable                                     |
| prepare_data_Levine_13dim.R | 404 https://www.cytobank.org/cytobank/experiments/46259   |
| prepare_data_Levine_32dim.R | 404 https://www.cytobank.org/cytobank/experiments/46102   |

if you know of other sources for such data, I would be happy to learn of them.

additionally, if you've extended/improved this framework for contrasting clustering approaches, I would appreciate an education in these efforts...

cheers!

**Comment by SamGG** [comment]
Hi,
Lukas will certainly post a better answer. Meanwhile you can start working with the prepared dataset from Lukas at https://flowrepository.org/id/FR-FCM-ZZPH. There are untransformed data there also.
Best.

**Comment by lmweber** [comment]
Yes, unfortunately some of those raw data links/repositories may no longer be maintained by the original authors.

However, as mentioned above, all our data files are also available in our own repository at https://flowrepository.org/id/FR-FCM-ZZPH, as described in our paper.

Also, since then, we have also made all of these datasets available through our `HDCytoData` Bioconductor package, which is available at http://bioconductor.org/packages/HDCytoData, and described in our paper at https://f1000research.com/articles/8-1459.
